### ISSUE TITLE
Errors are not propagated

### ISSUE THREAD

**Issue by PeterBurner** [gdaguilarc/appsync-cognito-query#2]
Could you please remove [this](https://github.com/gdaguilarc/appsync-cognito-query/blob/d0f06b5a5ed3a52ebd89717ea85aa5590cdde8f9/src/QueryManager.ts#L68) catch clause?  
Else errors cant be handled by the caller.

**Comment by gdaguilarc** [comment]
Thanks @PeterBurner  I will delete as soon as possible!

**Comment by PeterBurner** [comment]
Could you please also release this fix on npm?

**Comment by PeterBurner** [comment]
@gdaguilarc   
Could you please also release this fix on npm?

**Comment by gdaguilarc** [comment]
Sorry for the delay! I am still doing my bachelor and working at the same time. 

The new version is on NPM now

**Comment by PeterBurner** [comment]
no problem  
thanks
